[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
linea-testnet = "https://linea-sepolia.infura.io/v3/${INFURA_API_KEY}"
linea-mainnet = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
linea-testnet = { key = "${LINEASCAN_API_KEY}", chain = "59141", url = "https://api-sepolia.lineascan.build/api" }
linea-mainnet = { key = "${LINEASCAN_API_KEY}", url = "https://api.lineascan.build/api" }

